name: my_project
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.1
  logger: ^1.1.0
  supabase: ^1.2.0
  get_it: ^7.2.0
  json_annotation:

dev_dependencies:
  build_runner:
  json_serializable:
  mocktail: ^0.3.0
  test: ^1.19.2
